---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
spec:
  releaseName: logstash
  chart:
    spec:
      chart: logstash
      sourceRef:
        kind: HelmRepository
        name: elastic
      version: "^7.0.0"
  interval: 1h0m0s
  values: {}
