---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../overlays/logstash-index-apfeed-sqs

nameSuffix: '-capdev'

patchesJson6902:
- target:
    group: helm.toolkit.fluxcd.io
    version: v2beta1
    kind: HelmRelease
    name: logstash-index-apfeed-sqs-capdev
  patch: |-
    - op: add
      path: /spec/values/rbac
      value:
        create: true
    - op: replace
      path: /spec/releaseName
      value: logstash-index-apfeed-sqs-capdev
